// CREATE NEW DATA
export const ADD_LOCATION_REQUESTED = "ADD_LOCATION_REQUESTED";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILED = "ADD_LOCATION_FAILED";

// UPDATE DATA
export const UPDATE_LOCATION_REQUESTED = "UPDATE_LOCATION_REQUESTED";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAILED = "UPDATE_LOCATION_FAILED";

// VIEW DATA
export const VIEW_LOCATION_REQUESTED = "VIEW_LOCATION_REQUESTED";
export const VIEW_LOCATION_SUCCESS = "VIEW_LOCATION_SUCCESS";
export const VIEW_LOCATION_FAILED = "VIEW_LOCATION_FAILED";

// DELETE DATA
export const DELETE_LOCATION_REQUESTED = "DELETE_LOCATION_REQUESTED";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAILED = "DELETE_LOCATION_FAILED";

// REQUEST ALL DATA
export const GET_LOCATIONS_REQUESTED = "GET_LOCATIONS_REQUESTED";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILED = "GET_LOCATIONS_FAILED";
